spring.application.name=spring-ai-rag-with-ollama

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.init.pull-model-strategy=when_missing
spring.ai.ollama.init.timeout=60m
spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.embedding.options.model=nomic-embed-text

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=3623
# Spring AI will automatically create tables:vector_store
spring.ai.vectorstore.pgvector.initialize-schema=true

logging.level.org.springframework.ai.vectorstore=DEBUG


# Optional for fast speed

# Controls randomness. 0 → deterministic, 1 → creative
spring.ai.ollama.chat.options.temperature=0
# Limits answer size 200 tokens
spring.ai.ollama.chat.options.num-predict=200